-- Enable REPLICA IDENTITY FULL for realtime updates
ALTER TABLE public.messages REPLICA IDENTITY FULL;
ALTER TABLE public.calls REPLICA IDENTITY FULL;
ALTER TABLE public.profiles REPLICA IDENTITY FULL;